spring:
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/activiti_01?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123
  activiti:
    async-executor-activate: false
    process-definition-location-prefix: classpath:/processes/*/
    check-process-definitions: true
  thymeleaf:
    cache: false
    suffix: .html
mybatis:
  mapper-locations: classpath:/mapper/*.xml
  configLocation: classpath:/config/mybatis-config.xml
